apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-game-config
data:
  POSTGRES_DB: lugx_games
  POSTGRES_USER: lugx_user
  POSTGRES_PASSWORD: lugx_password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-game
  template:
    metadata:
      labels:
        app: postgres-game
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-game-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-game
spec:
  selector:
    app: postgres-game
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-order-config
data:
  POSTGRES_DB: lugx_orders
  POSTGRES_USER: lugx_user
  POSTGRES_PASSWORD: lugx_password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-order-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
spec:
  selector:
    app: postgres-order
  ports:
    - port: 5432
      targetPort: 5432
